export const ProductActionTypes = {
    SET_ENGINE_PRODUCTS: "SET_ENGINE_PRODUCTS",
    SET_PAINT_PRODUCTS: "SET_PAINT_PRODUCTS",
    SET_WHEEL_PRODUCTS: "SET_WHEEL_PRODUCTS",
    SET_OPTIONAL_PRODUCTS: "SET_OPTIONAL_PRODUCTS",
};

export const ResultActionTypes = {
    ADD_PRICE: "ADD_PRICE",
    REMOVE_PRICE: "REMOVE_PRICE",
    ENGINE_SELECTED: "ENGINE_SELECTED",
    ENGINE_DESELECTED: "ENGINE_DESELECTED",
    PAINT_SELECTED: "PAINT_SELECTED",
    PAINT_DESELECTED: "PAINT_DESELECTED",
    WHEEL_SELECTED: "WHEEL_SELECTED",
    WHEEL_DESELECTED: "WHEEL_DESELECTED",
    OPTIONAL_SELECTED: "OPTIONAL_SELECTED",
    OPTIONAL_DESELECTED: "OPTIONAL_DESELECTED"    
};